insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김경환',	6,	'01052382611',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김기덕',	6,	'01052382612',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김덕환',	6,	'01052382613',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김경완',	6,	'01052382610',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김동진',	6,	'01052382614',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김민숙',	6,	'01052382615',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김병수',	6,	'01052382616',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김상희',	6,	'01052382617',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김성현',	6,	'01052382618',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김용문',	6,	'01052382619',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김용문',	6,	'01052382620',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김정민',	6,	'01052382621',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김종윤',	6,	'01052382622',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김준영',	6,	'01052382623',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김홍석',	6,	'01052382624',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('노희성',	6,	'01052382625',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('류춘석',	6,	'01052382626',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('리슈빌',	6,	'01052382627',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('박정순',	6,	'01052382628',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('박홍규',	6,	'01052382629',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('반필규',	6,	'01052382630',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('반필규',	6,	'01052382631',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('배종성',	6,	'01052382632',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('백주요',	6,	'01052382633',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('변애희',	6,	'01052382634',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('서인찬',	6,	'01052382635',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('서현숙',	6,	'01052382636',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('신남철',	6,	'01052382637',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('심대영',	6,	'01052382638',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('안중희',	6,	'01052382639',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('양진호',	6,	'01052382640',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('윤민경',	6,	'01052382641',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('윤순백',	6,	'01052382642',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('이두영',	6,	'01052382643',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('이무형',	6,	'01052382644',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('이병민',	6,	'01052382645',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('이상진',	6,	'01052382646',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('이성민',	6,	'01052382647',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('이승호',	6,	'01052382648',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('이승호',	6,	'01052382649',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('이승훈',	6,	'01052382650',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('이승훈',	6,	'01052382651',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('이정용',	6,	'01052382652',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('임휘택',	6,	'01052382653',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('장윤수',	6,	'01052382654',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('정미숙',	6,	'01052382655',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('정병연',	6,	'01052382656',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('정원성',	6,	'01052382657',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('조옥자',	6,	'01052382658',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('조호영',	6,	'01052382659',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('진태석',	6,	'01052382660',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('최명용',	6,	'01052382661',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('최영범',	6,	'01052382662',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('추은주',	6,	'01052382663',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('탁용태',	6,	'01052382664',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('홍호영',	6,	'01052382665',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('홍호영',	6,	'01052382666',	'M');

insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	1	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	2	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	4	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	5	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	6	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	7	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	8	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	9	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	10	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	11	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	12	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	13	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	14	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	15	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	16	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	17	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	3	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	60	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	18	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	19	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	20	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	21	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	22	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	23	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	24	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	25	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	26	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	27	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	28	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	29	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	30	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	31	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	32	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	33	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	34	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	35	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	36	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	37	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	38	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	39	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	40	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	41	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	42	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	43	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	44	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	45	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	46	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	47	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	48	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	49	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	50	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	51	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	52	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	53	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	54	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	55	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	56	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	57	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	58	,7);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (floor(1+rand()*14),	59	,7);

//모든 event에 대한 match 정보 table 생성....
SELECT distinct tabletennis_competitions.`game`.*,
    match_t.match_id, match_t.match_order,
    participant.participant_id, participant.partner_id, participant.group_id,
    player.player_id, player.name, player.phone, player.grade, player.gender
FROM game, tabletennis_competitions.`match` as match_t, participant, player, event
where game.event=event.event_id and game.game_round=0 and game.game_id=match_t.game_id and participant.participant_id=match_t.parti_id
and player.player_id=participant.player_id
order by game.game_order, match_t.match_order;

insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (1,	1	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (1,	2	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	4	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	5	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	6	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	7	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	8	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	9	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	10	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	11	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	12	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	13	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	14	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	15	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	16	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	17	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	3	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	60	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	18	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	19	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	20	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	21	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	22	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	23	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	24	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	25	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	26	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	27	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	28	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	29	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	30	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	31	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	32	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	33	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	34	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	35	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	36	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	37	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	38	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	39	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	40	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	41	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	42	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	43	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	44	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	45	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	46	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	47	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	48	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	49	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	50	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	51	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	52	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	53	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	54	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	55	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	56	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	57	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	58	,9);
insert into tabletennis_competitions.participant (group_id, player_id, event_id, partner_id) values (floor(1+rand()*14),	59	,9);