insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김경환',	6,	'01052382611',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김기덕',	6,	'01052382612',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김덕환',	6,	'01052382613',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김경완',	6,	'01052382610',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김동진',	6,	'01052382614',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김민숙',	6,	'01052382615',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김병수',	6,	'01052382616',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김상희',	6,	'01052382617',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김성현',	6,	'01052382618',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김용문',	6,	'01052382619',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김용문',	6,	'01052382620',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김정민',	6,	'01052382621',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김종윤',	6,	'01052382622',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김준영',	6,	'01052382623',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('김홍석',	6,	'01052382624',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('노희성',	6,	'01052382625',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('류춘석',	6,	'01052382626',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('리슈빌',	6,	'01052382627',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('박정순',	6,	'01052382628',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('박홍규',	6,	'01052382629',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('반필규',	6,	'01052382630',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('반필규',	6,	'01052382631',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('배종성',	6,	'01052382632',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('백주요',	6,	'01052382633',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('변애희',	6,	'01052382634',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('서인찬',	6,	'01052382635',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('서현숙',	6,	'01052382636',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('신남철',	6,	'01052382637',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('심대영',	6,	'01052382638',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('안중희',	6,	'01052382639',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('양진호',	6,	'01052382640',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('윤민경',	6,	'01052382641',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('윤순백',	6,	'01052382642',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('이두영',	6,	'01052382643',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('이무형',	6,	'01052382644',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('이병민',	6,	'01052382645',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('이상진',	6,	'01052382646',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('이성민',	6,	'01052382647',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('이승호',	6,	'01052382648',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('이승호',	6,	'01052382649',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('이승훈',	6,	'01052382650',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('이승훈',	6,	'01052382651',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('이정용',	6,	'01052382652',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('임휘택',	6,	'01052382653',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('장윤수',	6,	'01052382654',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('정미숙',	6,	'01052382655',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('정병연',	6,	'01052382656',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('정원성',	6,	'01052382657',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('조옥자',	6,	'01052382658',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('조호영',	6,	'01052382659',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('진태석',	6,	'01052382660',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('최명용',	6,	'01052382661',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('최영범',	6,	'01052382662',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('추은주',	6,	'01052382663',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('탁용태',	6,	'01052382664',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('홍호영',	6,	'01052382665',	'M');
insert into tabletennis_competitions.player (name, grade, phone, gender) values ('홍호영',	6,	'01052382666',	'M');


insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	3	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	4	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	5	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	6	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	7	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	8	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	9	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	10	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	11	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	12	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	13	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	14	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	15	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	16	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	17	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	18	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	19	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	20	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	21	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	22	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	23	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	24	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	25	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	26	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	27	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	28	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	29	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	30	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	31	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	32	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	33	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	34	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	35	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	36	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	37	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	38	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	39	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	40	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	41	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	42	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	43	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	44	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	45	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	46	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	47	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	48	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	49	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	50	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	51	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	52	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	53	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	54	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	55	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	56	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	57	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	58	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	59	,6);
insert into tabletennis_competitions.participant (group_id, player_id, event_id) values (1,	60	,6);

//모든 event에 대한 match 정보 table 생성....
SELECT distinct tabletennis_competitions.`game`.*,
    match_t.match_id, match_t.match_order,
    participant.participant_id, participant.partner_id, participant.group_id,
    player.player_id, player.name, player.phone, player.grade, player.gender
FROM game, tabletennis_competitions.`match` as match_t, participant, player, event
where game.event=event.event_id and game.game_round=0 and game.game_id=match_t.game_id and participant.participant_id=match_t.parti_id
and player.player_id=participant.player_id
order by game.game_order, match_t.match_order;